#!/data/data/com.termux/files/usr/bin/bash
# Created by Hax4us
clear
#colors
green='\033[1;32m'
red='\033[1;31m'
yellow='\033[1;33m'
reset='\033[0m'
echo
echo -e "$green Please wait ..."
echo
echo -e "$yellow Dependencies Installing ..."
echo
echo -e "$red it can take upto 10 minutes (also depend on your net speed"
apt update -y && apt upgrade -y
apt install dirmngr gnupg-curl
repo()
{
	echo -e "$green repo_url is initializing ..."
	mkdir -p $PREFIX/etc/apt/sources.list.d
[ ! -f $PREFIX/etc/apt/sources.list.d/xeffyr.list ] && printf "deb https://termux.xeffyr.ml/ extra main x11" > $PREFIX/etc/apt/sources.list.d/xeffyr.list
echo -e "$yellow Ok"
echo
echo -e "$green Please wait ..."
apt update -y
apt install tigervnc xterm -y
clear
echo -e "$yellow Now you can use GUI using VNC ;)"
}
echo -e "$red Now you can exit but dont forget to subscribe my channel https://youtube.com/hax4us $reset"
echo
